/* Generated by rk_harness/tracecheck.py. Pinned by TRACE_HASH, never by VERIFIER_HASH. */
#include <stdint.h>

#define N_STATES 2
#define N_STAGES 2
#define K_CAP 2048

void rk_step(int16_t *y, int16_t h_q);

/* Recorded from the pinned Python evaluator, written into memory before the run. */
int16_t k_table[K_CAP];
int16_t acc_table[K_CAP];
int32_t k_index;
int32_t acc_mismatch;
int32_t k_overrun;

int16_t g_y[N_STATES];
int16_t g_hq;
int32_t g_steps;
int32_t g_mode;
int32_t g_trap;
int32_t g_ops;
int32_t g_shift_ok;
int32_t g_stopped;

static int32_t rk_op;
static int32_t rk_trap;

__attribute__((noinline, noclone))
void rk_rhs(const int16_t *y, int16_t *dy)
{
    int m;
    for (m = 0; m < N_STATES; m++) {
        if (k_index + m >= K_CAP) { k_overrun = 1; dy[m] = 0; continue; }
        if (y[m] != acc_table[k_index + m]) acc_mismatch = k_index + m + 1;
        dy[m] = k_table[k_index + m];
    }
    k_index += N_STATES;
}

/* The pinned Q15 primitives range-check operands and results and raise. Nothing
   wraps and nothing saturates, so the C has to trap where they raise. */
static int ck(int32_t v) { return (v < -32768 || v > 32767); }

int rk_step_checked(int16_t *y, int16_t h_q)
{
    int16_t hk[N_STAGES][N_STATES];
    int16_t acc[N_STATES];
    int16_t yn[N_STATES];
    int16_t k[N_STATES];
    int32_t r, va, vb;
    int m;

    /* stage 0 */
    for (m = 0; m < N_STATES; m++) acc[m] = y[m];
    rk_rhs(acc, k);
    for (m = 0; m < N_STATES; m++) {
        rk_op++;                                  /* q15_mul */
        va = (int32_t)k[m];
        vb = (int32_t)h_q;
        if (ck(va) || ck(vb)) { rk_trap = rk_op; return 1; }
        r = (va * vb) >> 15;
        if (ck(r)) { rk_trap = rk_op; return 1; }
        hk[0][m] = (int16_t)r;
    }

    /* stage 1 */
    for (m = 0; m < N_STATES; m++) acc[m] = y[m];
    for (m = 0; m < N_STATES; m++) {
        rk_op++;                                  /* q15_apply */
        r = ((int32_t)hk[0][m] * (int32_t)1) >> 1;
        if (ck(r)) { rk_trap = rk_op; return 1; }
        rk_op++;                                  /* q15_add */
        va = (int32_t)acc[m];
        if (ck(va) || ck(r) || ck(va + r)) { rk_trap = rk_op; return 1; }
        acc[m] = (int16_t)(va + r);
    }
    rk_rhs(acc, k);
    for (m = 0; m < N_STATES; m++) {
        rk_op++;                                  /* q15_mul */
        va = (int32_t)k[m];
        vb = (int32_t)h_q;
        if (ck(va) || ck(vb)) { rk_trap = rk_op; return 1; }
        r = (va * vb) >> 15;
        if (ck(r)) { rk_trap = rk_op; return 1; }
        hk[1][m] = (int16_t)r;
    }

    /* final combination over b */
    for (m = 0; m < N_STATES; m++) yn[m] = y[m];
    for (m = 0; m < N_STATES; m++) {
        rk_op++;                                  /* q15_apply */
        r = ((int32_t)hk[1][m] * (int32_t)1) >> 0;
        if (ck(r)) { rk_trap = rk_op; return 1; }
        rk_op++;                                  /* q15_add */
        va = (int32_t)yn[m];
        if (ck(va) || ck(r) || ck(va + r)) { rk_trap = rk_op; return 1; }
        yn[m] = (int16_t)(va + r);
    }
    for (m = 0; m < N_STATES; m++) y[m] = yn[m];
    return 0;
}

void rk_done(void);

void _start(void)
{
    int16_t y[N_STATES];
    int32_t s;
    int m;
    /* C leaves >> on a negative signed value to the implementation; the Q15 shift is
       arithmetic. If this compiler ever stopped agreeing, every result below is void. */
    g_shift_ok = ((((int32_t)-3) >> 1) == -2) ? 1 : 0;
    k_index = 0;
    acc_mismatch = 0;
    k_overrun = 0;
    rk_op = 0;
    rk_trap = 0;
    g_stopped = 0;
    for (m = 0; m < N_STATES; m++) y[m] = g_y[m];
    for (s = 0; s < g_steps; s++) {
        if (g_mode) {
            if (rk_step_checked(y, g_hq)) { g_stopped = s + 1; break; }
        } else {
            rk_step(y, g_hq);
        }
    }
    for (m = 0; m < N_STATES; m++) g_y[m] = y[m];
    g_trap = rk_trap;
    g_ops = rk_op;
    rk_done();
}

void __attribute__((noinline, noclone)) rk_done(void) { __asm__ volatile("nop"); }
